[general]
import = [
    "~/.config/alacritty/themes/themes/vscode.toml"
]

[mouse]
hide_when_typing = true

[env]
TERM = "xterm-256color"

[font.normal]
family = "MesloLGS NF"

[[keyboard.bindings]]
chars = "\u00021"
key = "Key1"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00022"
key = "Key2"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00023"
key = "Key3"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00024"
key = "Key4"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00025"
key = "Key5"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00026"
key = "Key6"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00027"
key = "Key7"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00028"
key = "Key8"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00029"
key = "Key9"
mods = "Command"

[scrolling]
history = 0

[terminal.shell]
args = ["new", "-As", "main"]
program = "/opt/homebrew/bin/tmux"

[window]
startup_mode = "SimpleFullscreen"
decorations = "None"

[terminal]
